set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'chriszarate/tmux-tasks'
set -g @plugin 'soyuka/tmux-current-pane-hostname'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-battery'
