POWERLEVEL9K_MODE='awesome-patched'
ZSH_THEME="powerlevel9k/powerlevel9k"

# POWERLEVEL9K_IP_INTERFACE='en0'
# POWERLEVEL9K_PUBLIC_IP_HOST='http://ident.me'

# zsh tmux settings
ZSH_TMUX_AUTOSTART='true'

## Powerlevel9k Settings
POWERLEVEL9K_HISTORY_BACKGROUND='green'

POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_CHRUBY_SHOW_ENGINE=false
POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -f`"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
BADGE="ツ"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{red} \UE12E `date +%T` $BADGE %f %F{yellow}❯ "

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('os_icon' 'context' dir_writable dir chruby vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status load)
# POWERLEVEL9K_TIME_FORMAT="%D{%T | %m.%d.%y}"